import type { VariantTechnique } from "./types";

export const COMMON_TLDS = [
  "com",
  "co",
  "net",
  "org",
  "io",
  "ai",
  "co.in",
  "in",
  "app",
  "dev",
  "xyz",
  "top",
  "info",
  "biz",
];

export const MULTI_PART_TLDS = new Set([
  "co.uk",
  "org.uk",
  "ac.uk",
  "gov.uk",
  "co.in",
  "com.au",
  "co.jp",
  "com.br",
]);

export const KEYBOARD_NEIGHBORS: Record<string, string[]> = {
  a: ["q", "w", "s", "z"],
  b: ["v", "g", "h", "n"],
  c: ["x", "d", "f", "v"],
  d: ["s", "e", "r", "f", "c", "x"],
  e: ["w", "s", "d", "r"],
  f: ["d", "r", "t", "g", "v", "c"],
  g: ["f", "t", "y", "h", "b", "v"],
  h: ["g", "y", "u", "j", "n", "b"],
  i: ["u", "j", "k", "o"],
  j: ["h", "u", "i", "k", "n", "m"],
  k: ["j", "i", "o", "l", "m"],
  l: ["k", "o", "p"],
  m: ["n", "j", "k"],
  n: ["b", "h", "j", "m"],
  o: ["i", "k", "l", "p"],
  p: ["o", "l"],
  q: ["w", "a"],
  r: ["e", "d", "f", "t"],
  s: ["a", "w", "e", "d", "x", "z"],
  t: ["r", "f", "g", "y"],
  u: ["y", "h", "j", "i"],
  v: ["c", "f", "g", "b"],
  w: ["q", "a", "s", "e"],
  x: ["z", "s", "d", "c"],
  y: ["t", "g", "h", "u"],
  z: ["a", "s", "x"],
  "0": ["9"],
  "1": ["2", "q"],
  "2": ["1", "3", "q", "w"],
  "3": ["2", "4", "w", "e"],
  "4": ["3", "5", "e", "r"],
  "5": ["4", "6", "r", "t"],
  "6": ["5", "7", "t", "y"],
  "7": ["6", "8", "y", "u"],
  "8": ["7", "9", "u", "i"],
  "9": ["8", "0", "i", "o"],
};

export const VARIANT_TECHNIQUE_WEIGHTS: Record<VariantTechnique, number> = {
  omission: 18,
  repetition: 14,
  character_swap: 15,
  keyboard_adjacency: 16,
  tld_swap: 12,
  hyphenation: 13,
};

export const PHISHY_URL_KEYWORDS = [
  "verify",
  "login",
  "secure",
  "wallet",
  "update",
  "invoice",
  "signin",
  "reset",
  "otp",
  "password",
  "claim",
  "urgent",
];

export const URL_SHORTENERS = new Set([
  "bit.ly",
  "tinyurl.com",
  "t.co",
  "goo.gl",
  "is.gd",
  "ow.ly",
  "rebrand.ly",
  "cutt.ly",
  "buff.ly",
  "tiny.cc",
]);

export const SUSPICIOUS_TLDS = new Set([
  "zip",
  "click",
  "top",
  "gq",
  "tk",
  "work",
  "support",
  "monster",
  "fit",
  "country",
]);

export const HIGH_VALUE_BRANDS = [
  "google",
  "microsoft",
  "apple",
  "amazon",
  "paypal",
  "github",
  "meta",
  "facebook",
  "instagram",
  "whatsapp",
  "telegram",
  "openai",
  "coinbase",
  "binance",
];
